pipeline {
  agent {
    docker {
      image 'node:12.14'
      args '-m 1G -v /home/jenkins/.ssh:/home/node/.ssh'
    }
  }

  stages {
    stage('Install') {
      steps {
        dir(path: 'web') {
          sh 'npm install'
        }
      }
    }

    stage('Build') {
      steps {
        dir(path: 'web') {
          sh 'export NODE_OPTIONS=--max_old_space_size=1000 && npm run build'
        }
      }
    }

    stage('Publish') {
      steps {
        dir(path: 'web') {
          sh 'scp -r .nuxt autojenkins@www.greatwebtech.cn:~/egg-server/web'
        }
      }
    }

    stage('Deploy') {
      steps {
        dir(path: 'web') {
          sh 'ssh autojenkins@www.greatwebtech.cn "cd ~/egg-server/web && npm run pm2:restart"'
        }
      }
    }
  }
}